# %% [markdown]
# # The Honest Metrics of Fraud Detection: companion notebook
#
# Companion to "The Honest Metrics of Fraud Detection: Precision, Recall, and the
# Investigator Capacity Constraint".
#
# - All data is **synthetic** (seed 42). No real bank, client, or transaction data.
# - Every figure in the article is regenerated by this notebook.
# - License: MIT.

# %% [markdown]
# ## 0. Setup

# %%
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

SEED = 42
rng = np.random.default_rng(SEED)
FIGDIR = Path(__file__).resolve().parent / "figures"
FIGDIR.mkdir(parents=True, exist_ok=True)
plt.rcParams.update({"figure.dpi": 150, "font.size": 9, "axes.grid": True, "grid.alpha": 0.3})

# %% [markdown]
# ## 1. A synthetic bank: one month of transactions and a strong model
#
# 30 days × 200,000 card transactions/day. Fraud prevalence is 1 in 500 (0.2%):
# realistic for a mixed consumer portfolio. The "model" is a synthetic score with
# ROC-AUC ≈ 0.97: strong by industry standards, deliberately not perfect.

# %%
DAYS = 30
TXN_PER_DAY = 200_000
N_TXN = DAYS * TXN_PER_DAY
PREVALENCE = 0.002

day = np.repeat(np.arange(1, DAYS + 1), TXN_PER_DAY)
is_fraud = rng.random(N_TXN) < PREVALENCE

amount = np.where(
    is_fraud,
    rng.lognormal(mean=np.log(420), sigma=0.9, size=N_TXN),
    rng.lognormal(mean=np.log(90), sigma=0.8, size=N_TXN),
).round(2)

score = np.where(
    is_fraud,
    np.clip(rng.normal(0.60, 0.10, N_TXN), 0, 1),
    np.clip(rng.normal(0.25, 0.16, N_TXN), 0, 1),
)

df = pd.DataFrame({"day": day, "score": score, "amount": amount, "is_fraud": is_fraud})
n_fraud = int(df.is_fraud.sum())
print(f"transactions: {N_TXN:,}  fraud: {n_fraud:,}  prevalence: {n_fraud/N_TXN:.4%}")
print(f"fraud £/day: {df[df.is_fraud].groupby('day').amount.sum().mean():,.0f}")

# %% [markdown]
# ## 2. Threshold-free metrics for the same model
#
# ROC-AUC via the rank (Mann-Whitney) statistic; average precision (step-wise,
# never trapezoidal) for the PR curve. The PR baseline equals prevalence, not 0.5.

# %%
def roc_auc(y, s):
    order = np.argsort(s, kind="mergesort")
    ranks = np.empty(len(s), dtype=float)
    ranks[order] = np.arange(1, len(s) + 1)
    n1, n0 = int(y.sum()), int((~y).sum())
    return (ranks[y.astype(bool)].sum() - n1 * (n1 + 1) / 2) / (n1 * n0)


def average_precision(y, s):
    order = np.argsort(s)[::-1]
    y_sorted = y[order]
    tp_cum = np.cumsum(y_sorted)
    precision = tp_cum / np.arange(1, len(y) + 1)
    return precision[y_sorted.astype(bool)].sum() / y.sum()


auc = roc_auc(df.is_fraud.values, df.score.values)
ap = average_precision(df.is_fraud.values, df.score.values)
print(f"ROC-AUC: {auc:.3f}   average precision (PR-AUC): {ap:.4f}   PR baseline (= prevalence): {PREVALENCE:.4f}")

# %%
# ROC and PR curves, computed exactly on the full 6M rows via sorted-score lookups
# (a strided subsample would carry almost no fraud positives at 1-in-500 prevalence).
fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.0))
fs = np.sort(df.loc[df.is_fraud, "score"].values)
ls = np.sort(df.loc[~df.is_fraud, "score"].values)
n1, n0 = len(fs), len(ls)
thresholds = np.linspace(0, 1, 201)
fpr, tpr, prec, rec = [], [], [], []
for t in thresholds:
    tp = n1 - np.searchsorted(fs, t, side="left")
    fp = n0 - np.searchsorted(ls, t, side="left")
    fn = n1 - tp
    fpr.append(fp / n0)
    tpr.append(tp / n1)
    prec.append(tp / max(1, tp + fp))
    rec.append(tp / max(1, tp + fn))
axes[0].plot(fpr, tpr, color="#1f77b4")
axes[0].set(xlabel="False positive rate", ylabel="True positive rate", title=f"ROC  (AUC = {auc:.3f})")
axes[1].plot(rec, prec, color="#d62728")
axes[1].axhline(PREVALENCE, ls="--", lw=1, color="grey")
axes[1].annotate("baseline = prevalence", (0.02, PREVALENCE + 0.02), fontsize=7, color="grey")
axes[1].set(xlabel="Recall", ylabel="Precision", xlim=(0, 1), ylim=(0, 1),
            title=f"PR  (AP = {ap:.3f}, baseline = {PREVALENCE:.3f})")
fig.suptitle("Fig 1: Same model, two lenses (1-in-500 prevalence)", fontsize=9)
fig.tight_layout()
fig.savefig(FIGDIR / "fig1_roc_vs_pr.png", bbox_inches="tight")
plt.close(fig)

# %% [markdown]
# ## 3. Capacity metrics: precision@N and value-recovered@N
#
# The daily queue is the top-N scored transactions of that day, N being what the
# investigation team can actually work. Nothing else gets a label.

# %%
def metrics_at_capacity(scores, amounts, fraud, n):
    order = np.argsort(scores)[::-1][:n]
    tp = int(fraud[order].sum())
    precision_at_n = tp / n
    value_at_n = amounts[order][fraud[order].astype(bool)].sum() / max(1e-9, amounts[fraud.astype(bool)].sum())
    return precision_at_n, value_at_n


daily = df.groupby("day")
# Log grid for the sweep, unioned with the exact capacities quoted in the article
# so printed rows are measured at their stated N, not a nearest grid point.
grid = np.unique(np.concatenate([
    np.logspace(np.log10(50), np.log10(20_000), 40).astype(int),
    [500, 1_000, 2_000, 5_000],
]))
rows = []
for n in grid:
    p, v = zip(*[metrics_at_capacity(g.score.values, g.amount.values, g.is_fraud.values, n)
                 for _, g in daily])
    rows.append({"N": n, "precision@N": float(np.mean(p)), "value@N": float(np.mean(v))})
cap = pd.DataFrame(rows)

for n in (500, 1_000, 2_000, 5_000):
    r = cap.iloc[(cap.N - n).abs().argmin()]
    print(f"N={int(r.N):>6,}/day   precision@N = {r['precision@N']:.1%}   value-recovered@N = {r['value@N']:.1%}")

# %% [markdown]
# ## 4. The capacity curve and expected value
#
# Expected value of running the queue at budget N: fraud pounds recovered minus
# the cost of working N alerts (triage cost £6/alert).

# %%
C_ALERT = 6.0
fraud_dollars_per_day = df[df.is_fraud].groupby("day").amount.sum().mean()
cap["recovered£/day"] = cap["value@N"] * fraud_dollars_per_day
cap["EV£/day"] = cap["recovered£/day"] - C_ALERT * cap.N
best = cap.loc[cap["EV£/day"].idxmax()]
print(f"EV-optimal budget N* = {int(best.N):,}/day  (EV = £{best['EV£/day']:,.0f}/day)")
cap.to_csv(FIGDIR.parent / "capacity_curve.csv", index=False)

# %%
N_STAR = 2_000  # staffing: what the team can actually work per day
fig, axes = plt.subplots(1, 2, figsize=(7.6, 3.2))
ax = axes[0]
ax.plot(cap.N, 100 * cap["precision@N"], color="#1f77b4", label="precision@N")
ax.set(xscale="log", xlabel="Daily alert budget N", ylabel="Precision at N (%)", ylim=(0, 100))
ax2 = ax.twinx()
ax2.plot(cap.N, 100 * cap["value@N"], color="#2ca02c", label="value-recovered@N")
ax2.set(ylabel="Fraud value recovered at N (%)", ylim=(0, 100))
ax.axvline(N_STAR, color="k", ls=":", lw=1)
ax.annotate("your team's N", (N_STAR * 1.1, 82), fontsize=7)
h1, l1 = ax.get_legend_handles_labels()
h2, l2 = ax2.get_legend_handles_labels()
ax.legend(h1 + h2, l1 + l2, loc="center left", fontsize=7)
ax.set_title("Capacity curve", fontsize=9)
axes[1].plot(cap.N, cap["EV£/day"] / 1000, color="#444")
axes[1].axvline(N_STAR, color="k", ls=":", lw=1)
axes[1].scatter([best.N], [best["EV£/day"] / 1000], color="#d62728", zorder=3)
axes[1].annotate(f"EV-max N = {int(best.N):,}", (best.N * 1.15, best["EV£/day"] / 1000 * 0.9), fontsize=7)
axes[1].set(xscale="log", xlabel="Daily alert budget N", ylabel="Expected value (£k/day)")
axes[1].set_title("Where staffing and value meet", fontsize=9)
fig.suptitle("Fig 2: The capacity curve: performance is a function of N, not of the model alone", fontsize=9)
fig.tight_layout()
fig.savefig(FIGDIR / "fig2_capacity_curve.png", bbox_inches="tight")
plt.close(fig)

# %% [markdown]
# ## 5. Value-aware queueing: score-ranked vs amount-aware ranking
#
# Reranking the same daily top-N by score × amount instead of score alone recovers
# more dollars at the same investigator headcount. This is a priority heuristic:
# with calibrated scores it becomes a true expected-loss ranking, and because the
# ordering mixes the score scale with amounts, recalibration changes the queue's
# composition (unlike a pure score-ranked queue).

# %%
def value_at_n_policy(g, n, policy):
    key = g.score.values if policy == "score" else g.score.values * g.amount.values
    order = np.argsort(key)[::-1][:n]
    return g.amount.values[order][g.is_fraud.values[order].astype(bool)].sum()


comp = []
for n in grid:
    v_score = np.mean([value_at_n_policy(g, n, "score") for _, g in daily])
    v_amount = np.mean([value_at_n_policy(g, n, "amount") for _, g in daily])
    comp.append({"N": n, "score-ranked": v_score / fraud_dollars_per_day,
                 "amount-ranked": v_amount / fraud_dollars_per_day})
comp = pd.DataFrame(comp)
at_capacity = comp[comp.N == N_STAR].iloc[0]
print(f"At N = {int(at_capacity.N):,}: score-ranked recovers {at_capacity['score-ranked']:.1%} of fraud £, "
      f"amount-ranked (score × amount) recovers {at_capacity['amount-ranked']:.1%}")

# %%
fig, ax = plt.subplots(figsize=(4.6, 3.0))
ax.plot(comp.N, 100 * comp["score-ranked"], color="#1f77b4", label="queue ranked by score")
ax.plot(comp.N, 100 * comp["amount-ranked"], color="#ff7f0e", label="queue ranked by score × amount")
ax.axvline(N_STAR, color="k", ls=":", lw=1)
ax.set(xscale="log", xlabel="Daily alert budget N", ylabel="Fraud value recovered (%)")
ax.set_title("Fig 3: Same model, same headcount,\ndifferent queue policy", fontsize=9)
ax.legend(fontsize=7)
fig.tight_layout()
fig.savefig(FIGDIR / "fig3_queue_policy.png", bbox_inches="tight")
plt.close(fig)

# %% [markdown]
# ## 6. The queue behind the threshold
#
# A fixed threshold emits a bursty arrival stream; the team clears a steady μ
# per day. Backlog evolves as B(d+1) = max(0, B(d) + arrivals(d) − μ). As
# utilization ρ → 1, backlog and alert age blow up, and aged alerts recover
# less (funds are gone within days).

# %%
QDAYS = 90
MU = 2_000  # alerts/day service capacity
shape = rng.lognormal(0, 0.30, QDAYS)
shape[:5] *= 1.8  # a rough week
shape = shape / shape.mean()

fig, ax = plt.subplots(figsize=(4.8, 3.0))
final = {}
for rho in (0.70, 0.85, 0.95, 1.05):
    arrivals = np.round(rho * MU * shape).astype(int)
    backlog = np.zeros(QDAYS, dtype=int)
    for d in range(QDAYS):
        prev = backlog[d - 1] if d > 0 else 0
        backlog[d] = max(0, prev + arrivals[d] - MU)
    final[rho] = int(backlog[-1])
    ax.plot(backlog, label=f"ρ = {rho:.2f}  (final backlog {backlog[-1]:,})", lw=1.4)
ax.set(xlabel="Day", ylabel="Unworked backlog (alerts)")
ax.set_title("Fig 4: A static threshold over a bursty stream", fontsize=9)
ax.legend(fontsize=7)
fig.tight_layout()
fig.savefig(FIGDIR / "fig4_queue.png", bbox_inches="tight")
plt.close(fig)
print("final backlogs:", final)

# %% [markdown]
# ## 7. Summary printed for the article

# %%
print("=== numbers quoted in the article ===")
print(f"prevalence:            1 in {1/PREVALENCE:,.0f}")
print(f"ROC-AUC:               {auc:.3f}")
print(f"average precision:     {ap:.4f}")
r1000 = cap[cap.N == 1_000].iloc[0]
r2000 = cap[cap.N == 2_000].iloc[0]
print(f"precision@1,000:       {r1000['precision@N']:.1%}")
print(f"precision@2,000:       {r2000['precision@N']:.1%}")
print(f"value@2,000:           {r2000['value@N']:.1%}")
print(f"EV-optimal N:          {int(best.N):,}/day")
print(f"amount-ranked gain@2,000: {at_capacity['amount-ranked'] - at_capacity['score-ranked']:+.1%} of fraud £")
